Fix unused symbol/variable warnings (#99)
* michelson/types: gather ctors together

* michelson/types: format `TypeError` contructors

* michelson/types: clean unused variables

* michelson/types: fix remaining warnings

* unit-test: delete unused symbols/vars

* michelson/common.md: address unused variable warnings

* michelson/syntax: move unused symbols out of main semantics

* michelson: remove IF_RIGHT macro from core semantics

* Avoid bison compilation error by importing MACRO everywhere (don't know why the crash happened)

* Macros: Implement IF_SOME, IF_LEFT

* Makefile: Add macro tests to unit and cross tests

Co-authored-by: Nishant Rodrigues <nishantjr@gmail.com>